

# This file was *autogenerated* from the file graph_generator.sage
from sage.all_cmdline import *   # import sage library

_sage_const_6 = Integer(6); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
nodes = _sage_const_6 
count = _sage_const_0 
for g in graphs.nauty_geng(f"{nodes} -c"):
     count += _sage_const_1 
     g.plot().save(f"./graphs_image/{nodes}nodes_graph/graph_{count}.png")

print(f"{count} graphs with {nodes} nodes generated.")


